### ISSUE TITLE
デザイン調査

### ISSUE THREAD

**Issue by luvmini511** [kanade0404/game-blog-v2#25]

**Comment by kanade0404** [comment]
- スマホはchrome dev toolsで確認できる程度の機種で良いです。（全部でなくて良いのでiphoneとpixelぐらい）
- ipadはできたらで（できなくても良い)
- SNSのwidgetあると良さそう

**Comment by kanade0404** [comment]
ブログはリニューアルしたら定期的に更新してサイトへの流入とかパフォーマンスとか計測していきたい。
