### ISSUE TITLE
ディレクトリ構成検討

### ISSUE THREAD

**Issue by kanade0404** [kanade0404/game-blog-v2#6]
## やること
Next.jsのディレクトリ構成をどうするか検討する。

## 完了条件
ディレクトリ構成の候補を提案する。

**Comment by kanade0404** [comment]
- https://github.com/alan2207/bulletproof-react
  - https://zenn.dev/meijin/articles/bulletproof-react-is-best-architecture

**Comment by luvmini511** [comment]
https://zenn.dev/sakito/articles/af87061a5016e6
